name: Publish (Linux)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install

      - name: Publish Linux
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          yarn postinstall && yarn build && yarn electron-builder --publish always --linux

      - name: Publish ARM64
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          yarn postinstall && yarn build && yarn electron-builder --publish always --arm64
